import {
  CategoryItem,
  PembukuanTransaction,
  RecurringTransaction,
  BankStatementTransaction,
} from "./types";

export interface AccountOption {
  id: string;
  name: string;
  type: string;
  accountNumber: string;
  balance: number;
  color: string;
}

export const PEMBUKUAN_ACCOUNTS: AccountOption[] = [
  {
    id: "acc-kas-utama",
    name: "Kas Utama Usaha",
    type: "Kas",
    accountNumber: "Kas Primer",
    balance: 24500000,
    color: "from-blue-600 to-indigo-600",
  },
  {
    id: "acc-operasional",
    name: "Kas Operasional Harian",
    type: "Kas",
    accountNumber: "Kas Harian",
    balance: 12850000,
    color: "from-sky-500 to-blue-600",
  },
  {
    id: "acc-simpanan",
    name: "Kas Simpanan & Cadangan",
    type: "Simpanan",
    accountNumber: "Pos Cadangan",
    balance: 8400000,
    color: "from-teal-500 to-emerald-600",
  },
  {
    id: "acc-qris",
    name: "QRIS & Dompet Digital",
    type: "E-Wallet",
    accountNumber: "Merchant QRIS",
    balance: 3150000,
    color: "from-cyan-500 to-blue-500",
  },
  {
    id: "acc-kas",
    name: "Kas Tunai Fisik (Laci)",
    type: "Tunai",
    accountNumber: "Laci Kasir",
    balance: 1950000,
    color: "from-emerald-500 to-teal-600",
  },
];

export const DEFAULT_CATEGORIES: CategoryItem[] = [
  // Income Categories
  {
    id: "cat-inc-salary",
    name: "Gaji Pokok",
    type: "income",
    iconName: "Wallet",
    colorClass: "text-emerald-400 bg-emerald-500/10 border-emerald-500/25",
    isDefault: true,
    description: "Gaji tetap bulanan atau pendapatan pokok pekerjaan",
    icon: "Wallet",
    color: "#10B981",
  },
  {
    id: "cat-inc-honor",
    name: "Honor",
    type: "income",
    iconName: "Briefcase",
    colorClass: "text-blue-400 bg-blue-500/10 border-blue-500/25",
    isDefault: true,
    description: "Honor proyek lepas, komisi tambahan, atau upah sampingan",
    icon: "Briefcase",
    color: "#3B82F6",
  },

  // Expense Categories (Sandang, Papan, Pangan)
  {
    id: "cat-exp-sandang",
    name: "Sandang",
    type: "expense",
    iconName: "ShoppingBag",
    colorClass: "text-purple-400 bg-purple-500/10 border-purple-500/25",
    isDefault: true,
    description: "Pakaian, celana, sepatu, dan kebutuhan sandang pribadi",
    icon: "ShoppingBag",
    color: "#A855F7",
  },
  {
    id: "cat-exp-papan",
    name: "Papan",
    type: "expense",
    iconName: "Home",
    colorClass: "text-amber-400 bg-amber-500/10 border-amber-500/25",
    isDefault: true,
    description: "Tempat tinggal, sewa hunian/kos, tagihan listrik, air & perawatan rumah",
    icon: "Home",
    color: "#F59E0B",
  },
  {
    id: "cat-exp-pangan",
    name: "Pangan",
    type: "expense",
    iconName: "Utensils",
    colorClass: "text-rose-400 bg-rose-500/10 border-rose-500/25",
    isDefault: true,
    description: "Makanan, minuman, bahan dapur, dan kebutuhan konsumsi sehari-hari",
    icon: "Utensils",
    color: "#EF4444",
  },
];

export const INITIAL_TRANSACTIONS: PembukuanTransaction[] = [
  {
    id: "trx-2026-001",
    date: "2026-08-25",
    time: "10:30",
    type: "income",
    amount: 5000000,
    categoryId: "cat-inc-salary",
    categoryName: "Gaji Pokok",
    accountId: "acc-mandiri",
    accountName: "Mandiri Bisnis Utama",
    description: "Penerimaan Gaji Pokok Bulanan",
    notes: "Gaji pokok masuk via transfer bank payroll",
    merchant: "Perusahaan Utama",
    status: "completed",
    tags: ["Gaji", "Payroll", "Lunas"],
    isReconciled: true,
    reconciledAt: "2026-08-25",
    createdAt: "2026-08-25T10:30:00Z",
    updatedAt: "2026-08-25T10:30:00Z",
  },
  {
    id: "trx-2026-002",
    date: "2026-08-25",
    time: "08:15",
    type: "expense",
    amount: 1420000,
    categoryId: "cat-exp-pangan",
    categoryName: "Pangan",
    accountId: "acc-bca",
    accountName: "BCA Operasional & Kas",
    description: "Belanja Bahan Dapur & Sembako Mingguan",
    notes: "Beras, minyak goreng, daging, sayuran segar",
    merchant: "Supermarket Segar Berkah",
    status: "completed",
    tags: ["Pangan", "Sembako"],
    attachments: [
      {
        id: "att-001",
        name: "Struk_Belanja_Pangan.jpg",
        url: "",
        size: 245000,
        type: "image/jpeg",
        uploadedAt: "2026-08-25T08:20:00Z",
      },
    ],
    isReconciled: true,
    reconciledAt: "2026-08-25",
    createdAt: "2026-08-25T08:15:00Z",
    updatedAt: "2026-08-25T08:15:00Z",
  },
  {
    id: "trx-2026-003",
    date: "2026-08-24",
    time: "16:45",
    type: "income",
    amount: 1850000,
    categoryId: "cat-inc-honor",
    categoryName: "Honor",
    accountId: "acc-gopay",
    accountName: "GoPay Merchant / QRIS",
    description: "Penerimaan Honor Project Lepas",
    notes: "Honor penyelesaian proyek sampingan",
    merchant: "Klien Digital Kreatif",
    status: "completed",
    tags: ["Honor", "Freelance"],
    isReconciled: true,
    reconciledAt: "2026-08-24",
    createdAt: "2026-08-24T16:45:00Z",
    updatedAt: "2026-08-24T16:45:00Z",
  },
  {
    id: "trx-2026-004",
    date: "2026-08-24",
    time: "14:00",
    type: "expense",
    amount: 380000,
    categoryId: "cat-exp-papan",
    categoryName: "Papan",
    accountId: "acc-bca",
    accountName: "BCA Operasional & Kas",
    description: "Pembayaran Token Listrik & Air Rumah",
    notes: "Tagihan listrik PLN token rumah & utilitas",
    merchant: "PLN Mobile",
    status: "completed",
    tags: ["Papan", "Listrik"],
    isReconciled: true,
    reconciledAt: "2026-08-24",
    createdAt: "2026-08-24T14:00:00Z",
    updatedAt: "2026-08-24T14:00:00Z",
  },
  {
    id: "trx-2026-005",
    date: "2026-08-23",
    time: "11:20",
    type: "expense",
    amount: 450000,
    categoryId: "cat-exp-sandang",
    categoryName: "Sandang",
    accountId: "acc-mandiri",
    accountName: "Mandiri Bisnis Utama",
    description: "Pembelian Pakaian & Perlengkapan Sandang",
    notes: "Baju kerja dan pakaian harian",
    merchant: "Toko Busana Modern",
    status: "completed",
    tags: ["Sandang", "Pakaian"],
    isReconciled: false,
    createdAt: "2026-08-23T11:20:00Z",
    updatedAt: "2026-08-23T11:20:00Z",
  },
  {
    id: "trx-2026-006",
    date: "2026-08-23",
    time: "09:00",
    type: "income",
    amount: 1200000,
    categoryId: "cat-inc-honor",
    categoryName: "Honor",
    accountId: "acc-bca",
    accountName: "BCA Operasional & Kas",
    description: "Honor Narasumber & Pendampingan",
    notes: "Honor workshop dan sesi sharing",
    merchant: "Komunitas Belajar",
    status: "completed",
    tags: ["Honor", "Narasumber"],
    isReconciled: false,
    createdAt: "2026-08-23T09:00:00Z",
    updatedAt: "2026-08-23T09:00:00Z",
  },
  {
    id: "trx-2026-007",
    date: "2026-08-22",
    time: "15:30",
    type: "expense",
    amount: 250000,
    categoryId: "cat-exp-pangan",
    categoryName: "Pangan",
    accountId: "acc-kas",
    accountName: "Kas Tunai Fisik",
    description: "Beli Sayur & Buah Segar Pasar Tradisional",
    notes: "Belanja kebutuhan dapur akhir pekan",
    merchant: "Pasar Tradisional",
    status: "completed",
    tags: ["Pangan", "Pasar"],
    isReconciled: false,
    createdAt: "2026-08-22T15:30:00Z",
    updatedAt: "2026-08-22T15:30:00Z",
  },
  {
    id: "trx-2026-008",
    date: "2026-08-22",
    time: "13:10",
    type: "expense",
    amount: 1500000,
    categoryId: "cat-exp-papan",
    categoryName: "Papan",
    accountId: "acc-mandiri",
    accountName: "Mandiri Bisnis Utama",
    description: "Iuran Sewa Tempat & Hunian Bulanan",
    notes: "Sewa tempat hunian periode Agustus",
    merchant: "Pengelola Hunian",
    status: "pending",
    tags: ["Papan", "Sewa", "Pending"],
    isReconciled: false,
    createdAt: "2026-08-22T13:10:00Z",
    updatedAt: "2026-08-22T13:10:00Z",
  },
  {
    id: "trx-2026-009",
    date: "2026-08-21",
    time: "10:00",
    type: "expense",
    amount: 320000,
    categoryId: "cat-exp-sandang",
    categoryName: "Sandang",
    accountId: "acc-mandiri",
    accountName: "Mandiri Bisnis Utama",
    description: "Sepatu Kerja & Kaos Kaki",
    notes: "Penggantian sepatu kerja harian",
    merchant: "Toko Sepatu Nyaman",
    status: "completed",
    tags: ["Sandang", "Sepatu"],
    isReconciled: false,
    createdAt: "2026-08-21T10:00:00Z",
    updatedAt: "2026-08-21T10:00:00Z",
  },
  {
    id: "trx-2026-010",
    date: "2026-08-20",
    time: "17:00",
    type: "expense",
    amount: 180000,
    categoryId: "cat-exp-pangan",
    categoryName: "Pangan",
    accountId: "acc-gopay",
    accountName: "GoPay Merchant / QRIS",
    description: "Makan Siang & Minuman Sehat",
    notes: "Makan siang bersama keluarga",
    merchant: "Warung Sehat Keluarga",
    status: "completed",
    tags: ["Pangan", "Kuliner"],
    isReconciled: false,
    createdAt: "2026-08-20T17:00:00Z",
    updatedAt: "2026-08-20T17:00:00Z",
  },
];

export const INITIAL_RECURRING: RecurringTransaction[] = [
  {
    id: "rec-001",
    name: "Sewa Hunian & Tempat Tinggal",
    type: "expense",
    amount: 1500000,
    categoryId: "cat-exp-papan",
    categoryName: "Papan",
    accountId: "acc-mandiri",
    accountName: "Mandiri Bisnis Utama",
    frequency: "monthly",
    startDate: "2026-01-01",
    nextOccurrenceDate: "2026-09-01",
    isActive: true,
    notes: "Pembayaran sewa tempat hunian setiap awal bulan",
    lastGeneratedAt: "2026-08-01",
    executionCount: 8,
  },
  {
    id: "rec-002",
    name: "Tagihan Listrik & Utilitas Hunian",
    type: "expense",
    amount: 350000,
    categoryId: "cat-exp-papan",
    categoryName: "Papan",
    accountId: "acc-bca",
    accountName: "BCA Operasional & Kas",
    frequency: "monthly",
    startDate: "2026-01-10",
    nextOccurrenceDate: "2026-09-10",
    isActive: true,
    notes: "Token listrik dan air bulanan",
    lastGeneratedAt: "2026-08-10",
    executionCount: 8,
  },
  {
    id: "rec-003",
    name: "Gaji Pokok Bulanan",
    type: "income",
    amount: 5000000,
    categoryId: "cat-inc-salary",
    categoryName: "Gaji Pokok",
    accountId: "acc-mandiri",
    accountName: "Mandiri Bisnis Utama",
    frequency: "monthly",
    startDate: "2026-01-25",
    nextOccurrenceDate: "2026-09-25",
    isActive: true,
    notes: "Gaji pokok bulanan masuk dari pemberi kerja",
    lastGeneratedAt: "2026-08-25",
    executionCount: 8,
  },
  {
    id: "rec-004",
    name: "Belanja Bahan Pangan & Dapur Mingguan",
    type: "expense",
    amount: 400000,
    categoryId: "cat-exp-pangan",
    categoryName: "Pangan",
    accountId: "acc-kas",
    accountName: "Kas Tunai Fisik",
    frequency: "weekly",
    startDate: "2026-01-05",
    nextOccurrenceDate: "2026-09-05",
    isActive: true,
    notes: "Kebutuhan pokok dapur mingguan",
    lastGeneratedAt: "2026-08-29",
    executionCount: 32,
  },
];

export const MOCK_BANK_STATEMENTS: BankStatementTransaction[] = [
  {
    id: "bank-stmt-01",
    date: "2026-08-25",
    description: "TRSF E-BANKING CR PANITIA SEMINAR 150 BENTO",
    amount: 4750000,
    type: "credit",
    balanceAfter: 24500000,
  },
  {
    id: "bank-stmt-02",
    date: "2026-08-25",
    description: "DEBIT EDC BCA KULAKAN DAGING PD JAGAL",
    amount: 1420000,
    type: "debit",
    balanceAfter: 19750000,
  },
  {
    id: "bank-stmt-03",
    date: "2026-08-24",
    description: "TRSF QRIS SETTLEMENT GOPAY MERCHANT",
    amount: 1850000,
    type: "credit",
    balanceAfter: 21170000,
  },
  {
    id: "bank-stmt-04",
    date: "2026-08-24",
    description: "AUTODEBIT TOKEN PLN 200RB X 2",
    amount: 380000,
    type: "debit",
    balanceAfter: 19320000,
  },
  {
    id: "bank-stmt-05",
    date: "2026-08-23",
    description: "BIAYA ADM BULANAN REKENING GIRO BISNIS",
    amount: 25000,
    type: "debit",
    balanceAfter: 19700000,
  },
  {
    id: "bank-stmt-06",
    date: "2026-08-22",
    description: "BUNGA JASA GIRO BANK PERIODE AGUSTUS",
    amount: 84500,
    type: "credit",
    balanceAfter: 19725000,
  },
];

export function formatCurrency(amount: number): string {
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
}

export function formatDateIndo(dateStr: string): string {
  try {
    const d = new Date(dateStr);
    return d.toLocaleDateString("id-ID", {
      day: "numeric",
      month: "short",
      year: "numeric",
    });
  } catch {
    return dateStr;
  }
}
