import {
  SavingsGoal,
  SavingsInsight,
  SavingsAchievement,
  AccountOption,
} from "./types";

export const ACCOUNT_OPTIONS: AccountOption[] = [
  {
    id: "acc-kas-utama",
    name: "Kas Utama Usaha",
    type: "Kas Utama",
    balance: 42500000,
    accountNumber: "Kas Primer",
  },
  {
    id: "acc-operasional",
    name: "Kas Operasional",
    type: "Kas Harian",
    balance: 28200000,
    accountNumber: "Pos Operasional",
  },
  {
    id: "acc-simpanan",
    name: "Pos Tabungan & Cadangan",
    type: "Simpanan",
    balance: 15600000,
    accountNumber: "Celengan Digital",
  },
  {
    id: "acc-gopay",
    name: "GoPay Merchant & Saldo",
    type: "E-Wallet",
    balance: 3450000,
    accountNumber: "0812-9833-2190",
  },
  {
    id: "acc-cash",
    name: "Kas Tunai & Amplop Usaha",
    type: "Kas Tunai",
    balance: 1200000,
    accountNumber: "KAS-MANUAL",
  },
];

export const CATEGORY_METADATA = {
  darurat: {
    label: "Dana Darurat",
    iconName: "ShieldCheck",
    colorClass: "text-emerald-400",
    bgClass: "bg-emerald-500/15 border-emerald-500/30 text-emerald-400",
    badgeClass: "text-emerald-400 bg-emerald-500/10 border-emerald-500/25",
    gradient: "from-emerald-500 via-teal-400 to-emerald-400",
    ringStrokeColor: "#10B981",
  },
  usaha: {
    label: "Bisnis & UMKM",
    iconName: "Store",
    colorClass: "text-amber-400",
    bgClass: "bg-amber-500/15 border-amber-500/30 text-amber-400",
    badgeClass: "text-amber-400 bg-amber-500/10 border-amber-500/25",
    gradient: "from-amber-500 via-orange-400 to-amber-400",
    ringStrokeColor: "#F59E0B",
  },
  gadget: {
    label: "Gadget & Kerja",
    iconName: "Laptop",
    colorClass: "text-blue-400",
    bgClass: "bg-blue-500/15 border-blue-500/30 text-blue-400",
    badgeClass: "text-blue-400 bg-blue-500/10 border-blue-500/25",
    gradient: "from-blue-500 via-indigo-400 to-blue-400",
    ringStrokeColor: "#3B82F6",
  },
  pendidikan: {
    label: "Pendidikan & Kursus",
    iconName: "GraduationCap",
    colorClass: "text-cyan-400",
    bgClass: "bg-cyan-500/15 border-cyan-500/30 text-cyan-400",
    badgeClass: "text-cyan-400 bg-cyan-500/10 border-cyan-500/25",
    gradient: "from-cyan-500 via-teal-400 to-cyan-400",
    ringStrokeColor: "#06B6D4",
  },
  properti: {
    label: "Properti & Tempat",
    iconName: "Home",
    colorClass: "text-indigo-400",
    bgClass: "bg-indigo-500/15 border-indigo-500/30 text-indigo-400",
    badgeClass: "text-indigo-400 bg-indigo-500/10 border-indigo-500/25",
    gradient: "from-indigo-500 via-purple-400 to-indigo-400",
    ringStrokeColor: "#6366F1",
  },
  kendaraan: {
    label: "Kendaraan Usaha",
    iconName: "Car",
    colorClass: "text-rose-400",
    bgClass: "bg-rose-500/15 border-rose-500/30 text-rose-400",
    badgeClass: "text-rose-400 bg-rose-500/10 border-rose-500/25",
    gradient: "from-rose-500 via-pink-400 to-rose-400",
    ringStrokeColor: "#F43F5E",
  },
  liburan: {
    label: "Ibadah & Liburan",
    iconName: "Plane",
    colorClass: "text-purple-400",
    bgClass: "bg-purple-500/15 border-purple-500/30 text-purple-400",
    badgeClass: "text-purple-400 bg-purple-500/10 border-purple-500/25",
    gradient: "from-purple-500 via-fuchsia-400 to-purple-400",
    ringStrokeColor: "#A855F7",
  },
  investasi: {
    label: "Investasi Logam/Aset",
    iconName: "TrendingUp",
    colorClass: "text-emerald-300",
    bgClass: "bg-emerald-600/15 border-emerald-600/30 text-emerald-300",
    badgeClass: "text-emerald-300 bg-emerald-600/10 border-emerald-600/25",
    gradient: "from-emerald-600 via-teal-500 to-emerald-400",
    ringStrokeColor: "#059669",
  },
  lainnya: {
    label: "Lainnya",
    iconName: "Target",
    colorClass: "text-slate-400",
    bgClass: "bg-slate-500/15 border-slate-500/30 text-slate-400",
    badgeClass: "text-slate-400 bg-slate-500/10 border-slate-500/25",
    gradient: "from-slate-500 to-slate-400",
    ringStrokeColor: "#94A3B8",
  },
};

export const INITIAL_SAVINGS_GOALS: SavingsGoal[] = [
  {
    id: "goal-darurat-umkm",
    name: "Dana Darurat Operasional Usaha",
    category: "darurat",
    categoryLabel: "Dana Darurat",
    userType: "UMKM",
    targetAmount: 25000000,
    currentAmount: 18500000,
    startDate: "2024-01-10",
    targetDate: "2024-12-31",
    priority: "tinggi",
    status: "aktif",
    description: "Cadangan kas 3 bulan operasional toko untuk antisipasi fluktuasi pasokan dan perbaikan alat.",
    iconName: "ShieldCheck",
    accentColor: "text-emerald-400",
    gradient: "from-emerald-500 via-teal-400 to-emerald-400",
    badgeClass: "text-emerald-400 bg-emerald-500/10 border-emerald-500/25",
    iconContainerClass: "bg-emerald-500/15 border-emerald-500/30 text-emerald-400",
    ringStrokeColor: "#10B981",
    autoSave: {
      enabled: true,
      frequency: "bulanan",
      amount: 1500000,
      sourceAccount: "BCA Bisnis & Operasional",
      nextDebitDate: "2024-10-25",
      dayOfMonth: 25,
    },
    milestones: [
      { level: 25, label: "Pondasi Awal (25%)", percentage: 25, reached: true, reachedAt: "2024-03-15", badgeName: "Perunggu", description: "Mencapai Rp 6.250.000" },
      { level: 50, label: "Separuh Jalan (50%)", percentage: 50, reached: true, reachedAt: "2024-06-20", badgeName: "Perak", description: "Mencapai Rp 12.500.000" },
      { level: 75, label: "Zona Aman (75%)", percentage: 75, reached: false, badgeName: "Emas", description: "Mencapai Rp 18.750.000" },
      { level: 100, label: "Benteng Sempurna (100%)", percentage: 100, reached: false, badgeName: "Platinum", description: "Mencapai Rp 25.000.000" },
    ],
    transactions: [
      { id: "tx-1", goalId: "goal-darurat-umkm", amount: 1500000, date: "2024-09-25", method: "Auto-Save", sourceAccount: "BCA Bisnis", notes: "Setoran otomatis bulanan", isAutoSave: true },
      { id: "tx-2", goalId: "goal-darurat-umkm", amount: 2000000, date: "2024-09-12", method: "Transfer", sourceAccount: "Mandiri Utama", notes: "Alokasi surplus omzet bazar akhir pekan" },
      { id: "tx-3", goalId: "goal-darurat-umkm", amount: 1500000, date: "2024-08-25", method: "Auto-Save", sourceAccount: "BCA Bisnis", notes: "Setoran otomatis bulanan", isAutoSave: true },
      { id: "tx-4", goalId: "goal-darurat-umkm", amount: 3000000, date: "2024-07-30", method: "Transfer", sourceAccount: "BCA Bisnis", notes: "Bonus invoice proyek katering selesai" },
    ],
    createdAt: "2024-01-10T08:00:00Z",
    updatedAt: "2024-09-25T14:30:00Z",
  },
  {
    id: "goal-laptop-kuliah",
    name: "Laptop Skripsi & Desain Grafis",
    category: "gadget",
    categoryLabel: "Gadget & Kerja",
    userType: "Mahasiswa",
    targetAmount: 16000000,
    currentAmount: 12000000,
    startDate: "2024-02-01",
    targetDate: "2024-11-15",
    priority: "tinggi",
    status: "aktif",
    description: "Upgrade laptop spesifikasi tinggi untuk olah data skripsi machine learning dan freelance design.",
    iconName: "Laptop",
    accentColor: "text-blue-400",
    gradient: "from-blue-500 via-indigo-400 to-blue-400",
    badgeClass: "text-blue-400 bg-blue-500/10 border-blue-500/25",
    iconContainerClass: "bg-blue-500/15 border-blue-500/30 text-blue-400",
    ringStrokeColor: "#3B82F6",
    autoSave: {
      enabled: true,
      frequency: "bulanan",
      amount: 1000000,
      sourceAccount: "Mandiri Tabungan Utama",
      nextDebitDate: "2024-10-28",
      dayOfMonth: 28,
    },
    milestones: [
      { level: 25, label: "Pondasi Awal (25%)", percentage: 25, reached: true, reachedAt: "2024-04-02", badgeName: "Perunggu", description: "Mencapai Rp 4.000.000" },
      { level: 50, label: "Separuh Jalan (50%)", percentage: 50, reached: true, reachedAt: "2024-07-10", badgeName: "Perak", description: "Mencapai Rp 8.000.000" },
      { level: 75, label: "Zona Matang (75%)", percentage: 75, reached: true, reachedAt: "2024-09-18", badgeName: "Emas", description: "Mencapai Rp 12.000.000" },
      { level: 100, label: "Laptop Impian (100%)", percentage: 100, reached: false, badgeName: "Platinum", description: "Mencapai Rp 16.000.000" },
    ],
    transactions: [
      { id: "tx-5", goalId: "goal-laptop-kuliah", amount: 1000000, date: "2024-09-28", method: "Auto-Save", sourceAccount: "Mandiri", notes: "Setoran otomatis gaji magang", isAutoSave: true },
      { id: "tx-6", goalId: "goal-laptop-kuliah", amount: 1500000, date: "2024-09-18", method: "Transfer", sourceAccount: "GoPay", notes: "Penghasilan freelance project UI/UX" },
      { id: "tx-7", goalId: "goal-laptop-kuliah", amount: 1000000, date: "2024-08-28", method: "Auto-Save", sourceAccount: "Mandiri", notes: "Setoran otomatis", isAutoSave: true },
    ],
    createdAt: "2024-02-01T09:00:00Z",
    updatedAt: "2024-09-28T10:00:00Z",
  },
  {
    id: "goal-ekspansi-usaha",
    name: "Modal Ekspansi & Mesin Kopi Baru",
    category: "usaha",
    categoryLabel: "Bisnis & UMKM",
    userType: "UMKM",
    targetAmount: 45000000,
    currentAmount: 18000000,
    startDate: "2024-03-01",
    targetDate: "2025-02-28",
    priority: "sedang",
    status: "aktif",
    description: "Pengadaan mesin espresso komersial 2-group dan renovasi area seating outdoor kedai.",
    iconName: "Store",
    accentColor: "text-amber-400",
    gradient: "from-amber-500 via-orange-400 to-amber-400",
    badgeClass: "text-amber-400 bg-amber-500/10 border-amber-500/25",
    iconContainerClass: "bg-amber-500/15 border-amber-500/30 text-amber-400",
    ringStrokeColor: "#F59E0B",
    autoSave: {
      enabled: true,
      frequency: "bulanan",
      amount: 3500000,
      sourceAccount: "BCA Bisnis & Operasional",
      nextDebitDate: "2024-10-30",
      dayOfMonth: 30,
    },
    milestones: [
      { level: 25, label: "Langkah Awal (25%)", percentage: 25, reached: true, reachedAt: "2024-05-14", badgeName: "Perunggu", description: "Mencapai Rp 11.250.000" },
      { level: 50, label: "Separuh Jalan (50%)", percentage: 50, reached: false, badgeName: "Perak", description: "Mencapai Rp 22.500.000" },
      { level: 75, label: "Akselerasi (75%)", percentage: 75, reached: false, badgeName: "Emas", description: "Mencapai Rp 33.750.000" },
      { level: 100, label: "Ekspansi Siap (100%)", percentage: 100, reached: false, badgeName: "Platinum", description: "Mencapai Rp 45.000.000" },
    ],
    transactions: [
      { id: "tx-8", goalId: "goal-ekspansi-usaha", amount: 3500000, date: "2024-09-30", method: "Auto-Save", sourceAccount: "BCA Bisnis", notes: "Setoran rutin laba ditahan", isAutoSave: true },
      { id: "tx-9", goalId: "goal-ekspansi-usaha", amount: 2500000, date: "2024-09-05", method: "Transfer", sourceAccount: "BRI Simpedes", notes: "Sisa kas acara workshop kopi" },
    ],
    createdAt: "2024-03-01T10:00:00Z",
    updatedAt: "2024-09-30T17:00:00Z",
  },
  {
    id: "goal-sertifikasi-ai",
    name: "Sertifikasi Cloud & AI Developer",
    category: "pendidikan",
    categoryLabel: "Pendidikan & Kursus",
    userType: "Mahasiswa",
    targetAmount: 4500000,
    currentAmount: 3600000,
    startDate: "2024-05-01",
    targetDate: "2024-10-20",
    priority: "sedang",
    status: "aktif",
    description: "Ujian sertifikasi internasional Google Cloud Professional Data Engineer.",
    iconName: "GraduationCap",
    accentColor: "text-cyan-400",
    gradient: "from-cyan-500 via-teal-400 to-cyan-400",
    badgeClass: "text-cyan-400 bg-cyan-500/10 border-cyan-500/25",
    iconContainerClass: "bg-cyan-500/15 border-cyan-500/30 text-cyan-400",
    ringStrokeColor: "#06B6D4",
    autoSave: {
      enabled: false,
      frequency: "bulanan",
      amount: 500000,
      sourceAccount: "GoPay / E-Wallet",
      nextDebitDate: "2024-10-20",
    },
    milestones: [
      { level: 25, label: "Registrasi (25%)", percentage: 25, reached: true, reachedAt: "2024-06-01", badgeName: "Perunggu", description: "Mencapai Rp 1.125.000" },
      { level: 50, label: "Tryout (50%)", percentage: 50, reached: true, reachedAt: "2024-07-20", badgeName: "Perak", description: "Mencapai Rp 2.250.000" },
      { level: 75, label: "Siap Ujian (75%)", percentage: 75, reached: true, reachedAt: "2024-09-10", badgeName: "Emas", description: "Mencapai Rp 3.375.000" },
      { level: 100, label: "Voucher Terbeli (100%)", percentage: 100, reached: false, badgeName: "Platinum", description: "Mencapai Rp 4.500.000" },
    ],
    transactions: [
      { id: "tx-10", goalId: "goal-sertifikasi-ai", amount: 600000, date: "2024-09-10", method: "Transfer", sourceAccount: "GoPay", notes: "Uang saku asisten praktikum" },
      { id: "tx-11", goalId: "goal-sertifikasi-ai", amount: 1000000, date: "2024-08-15", method: "Transfer", sourceAccount: "Mandiri", notes: "Tabungan rutin" },
    ],
    createdAt: "2024-05-01T11:00:00Z",
    updatedAt: "2024-09-10T12:00:00Z",
  },
  {
    id: "goal-dp-ruko",
    name: "DP Ruko & Gudang Penyimpanan",
    category: "properti",
    categoryLabel: "Properti & Tempat",
    userType: "UMKM",
    targetAmount: 80000000,
    currentAmount: 24000000,
    startDate: "2024-01-01",
    targetDate: "2025-12-31",
    priority: "rendah",
    status: "aktif",
    description: "Uang muka sewa jangka panjang 5 tahun ruko 2 lantai untuk ekspansi packaging dan logistik.",
    iconName: "Home",
    accentColor: "text-indigo-400",
    gradient: "from-indigo-500 via-purple-400 to-indigo-400",
    badgeClass: "text-indigo-400 bg-indigo-500/10 border-indigo-500/25",
    iconContainerClass: "bg-indigo-500/15 border-indigo-500/30 text-indigo-400",
    ringStrokeColor: "#6366F1",
    autoSave: {
      enabled: true,
      frequency: "bulanan",
      amount: 4000000,
      sourceAccount: "BCA Bisnis & Operasional",
      nextDebitDate: "2024-10-25",
      dayOfMonth: 25,
    },
    milestones: [
      { level: 25, label: "Booking Fee (25%)", percentage: 25, reached: true, reachedAt: "2024-07-01", badgeName: "Perunggu", description: "Mencapai Rp 20.000.000" },
      { level: 50, label: "Separuh DP (50%)", percentage: 50, reached: false, badgeName: "Perak", description: "Mencapai Rp 40.000.000" },
      { level: 75, label: "Pelunasan DP (75%)", percentage: 75, reached: false, badgeName: "Emas", description: "Mencapai Rp 60.000.000" },
      { level: 100, label: "Kunci di Tangan (100%)", percentage: 100, reached: false, badgeName: "Platinum", description: "Mencapai Rp 80.000.000" },
    ],
    transactions: [
      { id: "tx-12", goalId: "goal-dp-ruko", amount: 4000000, date: "2024-09-25", method: "Auto-Save", sourceAccount: "BCA Bisnis", notes: "Setoran otomatis bulanan", isAutoSave: true },
      { id: "tx-13", goalId: "goal-dp-ruko", amount: 5000000, date: "2024-08-10", method: "Transfer", sourceAccount: "BCA Bisnis", notes: "Dividen laba semester 1" },
    ],
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-09-25T14:30:00Z",
  },
  {
    id: "goal-umrah-keluarga",
    name: "Tabungan Ibadah Umrah Bersama",
    category: "liburan",
    categoryLabel: "Ibadah & Liburan",
    userType: "Umum",
    targetAmount: 35000000,
    currentAmount: 35000000,
    startDate: "2023-09-01",
    targetDate: "2024-09-15",
    priority: "tinggi",
    status: "tercapai",
    description: "Alhamdulillah target tabungan umrah telah selesai dikumpulkan 100% tepat waktu.",
    iconName: "Plane",
    accentColor: "text-purple-400",
    gradient: "from-purple-500 via-fuchsia-400 to-purple-400",
    badgeClass: "text-purple-400 bg-purple-500/10 border-purple-500/25",
    iconContainerClass: "bg-purple-500/15 border-purple-500/30 text-purple-400",
    ringStrokeColor: "#A855F7",
    autoSave: {
      enabled: false,
      frequency: "bulanan",
      amount: 2500000,
      sourceAccount: "Mandiri Tabungan Utama",
      nextDebitDate: "2024-09-15",
    },
    milestones: [
      { level: 25, label: "Niat & DP (25%)", percentage: 25, reached: true, reachedAt: "2023-12-01", badgeName: "Perunggu", description: "Mencapai Rp 8.750.000" },
      { level: 50, label: "Separuh Perjalanan (50%)", percentage: 50, reached: true, reachedAt: "2024-03-10", badgeName: "Perak", description: "Mencapai Rp 17.500.000" },
      { level: 75, label: "Konfirmasi Paket (75%)", percentage: 75, reached: true, reachedAt: "2024-06-25", badgeName: "Emas", description: "Mencapai Rp 26.250.000" },
      { level: 100, label: "Siap Berangkat (100%)", percentage: 100, reached: true, reachedAt: "2024-09-15", badgeName: "Platinum", description: "Mencapai Rp 35.000.000" },
    ],
    transactions: [
      { id: "tx-14", goalId: "goal-umrah-keluarga", amount: 5000000, date: "2024-09-15", method: "Transfer", sourceAccount: "Mandiri", notes: "Pelunasan sisa target akhir" },
    ],
    createdAt: "2023-09-01T07:00:00Z",
    updatedAt: "2024-09-15T09:00:00Z",
  },
];

export const INITIAL_SAVINGS_INSIGHTS: SavingsInsight[] = [
  {
    id: "ins-1",
    title: "Akselerasi Dana Darurat Usaha",
    description: "Menambahkan surplus Rp 500.000 per minggu dari omzet kas dapat mempercepat tercapainya Dana Darurat 26 hari lebih awal sebelum akhir tahun.",
    impact: "tinggi",
    categoryTag: "Optimasi Arus Kas",
    actionType: "add_money",
    actionLabel: "Setor Kas Sekarang",
    goalIdTarget: "goal-darurat-umkm",
    potentialSavings: 2000000,
  },
  {
    id: "ins-2",
    title: "Pangkas Pengeluaran F&B Konsumtif",
    description: "Data monitor menunjukkan pengeluaran kopi & jajan harian mencapai Rp 1.450.000/bln. Alihkan 25% ke pos Laptop Skripsi untuk menutup kekurangan target bulan depan.",
    impact: "sedang",
    categoryTag: "Penghematan Harian",
    actionType: "add_money",
    actionLabel: "Alokasikan ke Laptop",
    goalIdTarget: "goal-laptop-kuliah",
    potentialSavings: 362500,
  },
  {
    id: "ins-3",
    title: "Jadwalkan Auto-Save Pasca Terima Invoice",
    description: "Rata-rata klien melunasi invoice di tanggal 24-25. Menjadwalkan debit otomatis di tanggal 26 memastikan modal ekspansi terisi konsisten tanpa terpakai.",
    impact: "tinggi",
    categoryTag: "Otomasi Finansial",
    actionType: "setup_autosave",
    actionLabel: "Konfigurasi Jadwal",
    goalIdTarget: "goal-ekspansi-usaha",
    potentialSavings: 3500000,
  },
];

export const INITIAL_ACHIEVEMENTS: SavingsAchievement[] = [
  {
    id: "ach-1",
    title: "Langkah Pertama",
    description: "Membuat pos target tabungan pertama di FINUSA.",
    icon: "Sparkles",
    category: "Aktivasi",
    progress: 1,
    maxProgress: 1,
    unlocked: true,
    unlockedDate: "10 Jan 2024",
    tier: "Bronze",
  },
  {
    id: "ach-2",
    title: "Separuh Perjalanan (50%)",
    description: "Mencapai minimal 50% target pada salah satu pos tabungan.",
    icon: "Award",
    category: "Milestone",
    progress: 1,
    maxProgress: 1,
    unlocked: true,
    unlockedDate: "20 Jun 2024",
    tier: "Silver",
  },
  {
    id: "ach-3",
    title: "Target Juara (100%)",
    description: "Menuntaskan setoran hingga 100% target tercapai penuh.",
    icon: "Trophy",
    category: "Penyelesaian",
    progress: 1,
    maxProgress: 1,
    unlocked: true,
    unlockedDate: "15 Sep 2024",
    tier: "Platinum",
  },
  {
    id: "ach-4",
    title: "Disiplin Finansial 30 Hari",
    description: "Menabung atau menyisihkan dana secara konsisten selama 30 hari berturut-turut.",
    icon: "Flame",
    category: "Konsistensi",
    progress: 30,
    maxProgress: 30,
    unlocked: true,
    unlockedDate: "30 Agt 2024",
    tier: "Gold",
  },
  {
    id: "ach-5",
    title: "Akumulasi Tabungan Rp 50 Juta+",
    description: "Total saldo terkumpul di seluruh pos menembus Rp 50.000.000.",
    icon: "Coins",
    category: "Volume",
    progress: 111100000,
    maxProgress: 50000000,
    unlocked: true,
    unlockedDate: "05 Sep 2024",
    tier: "Gold",
  },
  {
    id: "ach-6",
    title: "Manajer Multitask (5 Pos Aktif)",
    description: "Mengelola dan mendanai 5 atau lebih pos tabungan secara bersamaan.",
    icon: "Layers",
    category: "Perencanaan",
    progress: 5,
    maxProgress: 5,
    unlocked: true,
    unlockedDate: "01 Mei 2024",
    tier: "Silver",
  },
];
