import {
  Account,
  BudgetCategory,
  CashflowPoint,
  CategoryBreakdownPoint,
  DashboardSummary,
  PeriodType,
  Transaction,
} from "./types";

export const MOCK_ACCOUNTS: Account[] = [
  {
    id: "acc-1",
    name: "Kas Utama Usaha",
    type: "cash",
    balance: 8450000,
    accountNumber: "Kas Primer",
    institution: "Kas Toko",
    color: "#2563EB",
  },
  {
    id: "acc-2",
    name: "Kas Operasional",
    type: "cash",
    balance: 14200000,
    accountNumber: "Kas Harian",
    institution: "Kas Operasional",
    color: "#0284C7",
  },
  {
    id: "acc-3",
    name: "GoPay Utama",
    type: "e_wallet",
    balance: 850000,
    accountNumber: "0812 •••• 4920",
    institution: "GoTo Financial",
    color: "#00AED6",
  },
  {
    id: "acc-4",
    name: "OVO Cash",
    type: "e_wallet",
    balance: 420000,
    accountNumber: "0812 •••• 4920",
    institution: "OVO",
    color: "#4F46E5",
  },
  {
    id: "acc-5",
    name: "Kas Tunai & Dompet",
    type: "cash",
    balance: 1150000,
    accountNumber: "Fisik",
    institution: "Dompet Pribadi",
    color: "#10B981",
  },
];

export const MOCK_BUDGETS: BudgetCategory[] = [
  {
    id: "bdg-1",
    categoryId: "operasional",
    categoryName: "Operasional Usaha",
    iconName: "Briefcase",
    budgetAmount: 4500000,
    spentAmount: 3850000,
    period: "monthly",
  },
  {
    id: "bdg-2",
    categoryId: "makanan",
    categoryName: "Makanan & Minuman",
    iconName: "Utensils",
    budgetAmount: 2000000,
    spentAmount: 1450000,
    period: "monthly",
  },
  {
    id: "bdg-3",
    categoryId: "belanja",
    categoryName: "Belanja & Kebutuhan",
    iconName: "ShoppingCart",
    budgetAmount: 1800000,
    spentAmount: 1720000,
    period: "monthly",
  },
  {
    id: "bdg-4",
    categoryId: "transportasi",
    categoryName: "Transportasi",
    iconName: "Car",
    budgetAmount: 800000,
    spentAmount: 520000,
    period: "monthly",
  },
  {
    id: "bdg-5",
    categoryId: "utilitas",
    categoryName: "Utilitas & Tagihan",
    iconName: "Zap",
    budgetAmount: 900000,
    spentAmount: 875000,
    period: "monthly",
  },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: "trx-01",
    date: "2026-08-24",
    description: "Pendapatan Catering Acara Seminar",
    category: "Pendapatan Usaha",
    categoryId: "income_business",
    account: "Mandiri Bisnis",
    accountId: "acc-2",
    amount: 3450000,
    type: "income",
    status: "completed",
    merchant: "BEM Universitas",
    notes: "Pelunasan pesanan 70 kotak paket makan siang",
  },
  {
    id: "trx-02",
    date: "2026-08-23",
    description: "Kulakan Bahan Baku Tepung & Minyak",
    category: "Operasional Usaha",
    categoryId: "operasional",
    account: "Mandiri Bisnis",
    accountId: "acc-2",
    amount: 850000,
    type: "expense",
    status: "completed",
    merchant: "Toko Grosir Berkah Jaya",
    notes: "Stok mingguan produksi kue",
  },
  {
    id: "trx-03",
    date: "2026-08-23",
    description: "Proyek Freelance UI/UX Landing Page",
    category: "Freelance & Proyek",
    categoryId: "income_freelance",
    account: "BCA Tahapan",
    accountId: "acc-1",
    amount: 2800000,
    type: "income",
    status: "completed",
    merchant: "Klien Digital Agency",
    notes: "Termin ke-2 perancangan dashboard web",
  },
  {
    id: "trx-04",
    date: "2026-08-22",
    description: "Belanja Kemasan & Box Packaging",
    category: "Operasional Usaha",
    categoryId: "operasional",
    account: "Mandiri Bisnis",
    accountId: "acc-2",
    amount: 420000,
    type: "expense",
    status: "completed",
    merchant: "Percetakan Surya Graha",
    notes: "Cetak 200 pcs box kardus custom logo",
  },
  {
    id: "trx-05",
    date: "2026-08-22",
    description: "Bensin Motor & Parkir Kampus",
    category: "Transportasi",
    categoryId: "transportasi",
    account: "Kas Tunai & Dompet",
    accountId: "acc-5",
    amount: 65000,
    type: "expense",
    status: "completed",
    merchant: "SPBU Pertamina 34-12401",
    notes: "Isi Pertalite full tank + parkir perpustakaan",
  },
  {
    id: "trx-06",
    date: "2026-08-21",
    description: "Makan Siang & Kopi Diskusi Tim",
    category: "Makanan & Minuman",
    categoryId: "makanan",
    account: "GoPay Utama",
    accountId: "acc-3",
    amount: 92000,
    type: "expense",
    status: "completed",
    merchant: "Kopi Kenangan & Warung Bu Sri",
    notes: "Diskusi target penjualan mingguan",
  },
  {
    id: "trx-07",
    date: "2026-08-20",
    description: "Penjualan Toko Offline Harian",
    category: "Pendapatan Usaha",
    categoryId: "income_business",
    account: "Mandiri Bisnis",
    accountId: "acc-2",
    amount: 1720000,
    type: "income",
    status: "completed",
    merchant: "Kasir Toko",
    notes: "Total rekap transaksi kasir hari Kamis",
  },
  {
    id: "trx-08",
    date: "2026-08-20",
    description: "Listrik Token PLN & Wifi Usaha",
    category: "Utilitas & Tagihan",
    categoryId: "utilitas",
    account: "BCA Tahapan",
    accountId: "acc-1",
    amount: 375000,
    type: "expense",
    status: "completed",
    merchant: "PLN & Biznet Home",
    notes: "Token 200rb + Tagihan Internet bulanan",
  },
  {
    id: "trx-09",
    date: "2026-08-19",
    description: "Belanja Supermarket Kebutuhan Dapur",
    category: "Belanja & Kebutuhan",
    categoryId: "belanja",
    account: "BCA Tahapan",
    accountId: "acc-1",
    amount: 345000,
    type: "expense",
    status: "completed",
    merchant: "Superindo Karanganyar",
    notes: "Kebutuhan pokok mingguan rumah",
  },
  {
    id: "trx-10",
    date: "2026-08-18",
    description: "Vitamin & Suplemen Daya Tahan Tubuh",
    category: "Kesehatan",
    categoryId: "kesehatan",
    account: "GoPay Utama",
    accountId: "acc-3",
    amount: 135000,
    type: "expense",
    status: "completed",
    merchant: "Apotek K-24",
    notes: "Beli vitamin C dan madu",
  },
  {
    id: "trx-11",
    date: "2026-08-17",
    description: "Penjualan Spesial Promo Kemerdekaan",
    category: "Pendapatan Usaha",
    categoryId: "income_business",
    account: "Mandiri Bisnis",
    accountId: "acc-2",
    amount: 2650000,
    type: "income",
    status: "completed",
    merchant: "Toko & WhatsApp Order",
    notes: "Paket bundling diskon 17%",
  },
  {
    id: "trx-12",
    date: "2026-08-16",
    description: "Langganan Cloud Server & Database",
    category: "Operasional Usaha",
    categoryId: "operasional",
    account: "BCA Tahapan",
    accountId: "acc-1",
    amount: 210000,
    type: "expense",
    status: "completed",
    merchant: "Railway & Vercel Pro",
    notes: "Biaya infrastruktur hosting aplikasi",
  },
  {
    id: "trx-13",
    date: "2026-08-15",
    description: "Gaji Asisten Part-time Toko",
    category: "Operasional Usaha",
    categoryId: "operasional",
    account: "Mandiri Bisnis",
    accountId: "acc-2",
    amount: 1200000,
    type: "expense",
    status: "completed",
    merchant: "Transfer Karyawan",
    notes: "Honor paruh waktu periode 1-15 Agustus",
  },
  {
    id: "trx-14",
    date: "2026-08-14",
    description: "Biaya Percetakan Banner & Brosur",
    category: "Operasional Usaha",
    categoryId: "operasional",
    account: "Kas Tunai & Dompet",
    accountId: "acc-5",
    amount: 165000,
    type: "expense",
    status: "completed",
    merchant: "Digital Print Murah",
    notes: "X-Banner display promosi toko",
  },
  {
    id: "trx-15",
    date: "2026-08-13",
    description: "Makan Malam Bersama Keluarga",
    category: "Makanan & Minuman",
    categoryId: "makanan",
    account: "OVO Cash",
    accountId: "acc-4",
    amount: 185000,
    type: "expense",
    status: "completed",
    merchant: "Rumah Makan Padang Sederhana",
    notes: "Santap malam akhir pekan",
  },
  {
    id: "trx-16",
    date: "2026-08-12",
    description: "Buku Referensi & Modul Perkuliahan",
    category: "Pendidikan & Karir",
    categoryId: "pendidikan",
    account: "BCA Tahapan",
    accountId: "acc-1",
    amount: 175000,
    type: "expense",
    status: "completed",
    merchant: "Toko Buku Gramedia",
    notes: "Buku Metodologi Penelitian Akuntansi",
  },
  {
    id: "trx-17",
    date: "2026-08-10",
    description: "Dividen & Bagi Hasil Reksadana",
    category: "Investasi",
    categoryId: "income_investment",
    account: "BCA Tahapan",
    accountId: "acc-1",
    amount: 480000,
    type: "income",
    status: "completed",
    merchant: "Bibit Reksadana Pasar Uang",
    notes: "Imbal hasil investasi bulanan",
  },
  {
    id: "trx-18",
    date: "2026-08-08",
    description: "Servis Rutin Sepeda Motor",
    category: "Transportasi",
    categoryId: "transportasi",
    account: "Kas Tunai & Dompet",
    accountId: "acc-5",
    amount: 220000,
    type: "expense",
    status: "completed",
    merchant: "Bengkel Resmi AHASS",
    notes: "Ganti oli mesin, oli gardan, dan kampas rem",
  },
  {
    id: "trx-19",
    date: "2026-08-05",
    description: "Penjualan Produk Batch Pertama",
    category: "Pendapatan Usaha",
    categoryId: "income_business",
    account: "Mandiri Bisnis",
    accountId: "acc-2",
    amount: 2450000,
    type: "income",
    status: "completed",
    merchant: "Toko & Reseller",
    notes: "Pesanan awal bulan dari 3 mitra reseller",
  },
  {
    id: "trx-20",
    date: "2026-08-02",
    description: "Langganan Spotify Family & YouTube",
    category: "Hiburan & Rekreasi",
    categoryId: "hiburan",
    account: "GoPay Utama",
    accountId: "acc-3",
    amount: 86000,
    type: "expense",
    status: "completed",
    merchant: "Google Play Store",
    notes: "Autodebit langganan hiburan bulanan",
  },
];

export const MOCK_SUMMARIES: Record<PeriodType, DashboardSummary> = {
  this_month: {
    period: "this_month",
    totalBalance: 25070000,
    totalIncome: 13550000,
    totalExpense: 8415000,
    netCashflow: 5135000,
    savingRate: 37.9,
    kpis: {
      balance: {
        title: "Total Saldo Kas",
        value: 25070000,
        previousValue: 21250000,
        changePercentage: 17.9,
        isPositive: true,
        trendText: "vs bulan lalu",
      },
      income: {
        title: "Total Pemasukan",
        value: 13550000,
        previousValue: 11800000,
        changePercentage: 14.8,
        isPositive: true,
        trendText: "vs bulan lalu",
      },
      expense: {
        title: "Total Pengeluaran",
        value: 8415000,
        previousValue: 8950000,
        changePercentage: -5.9,
        isPositive: true, // Spending reduction is positive
        trendText: "lebih hemat vs lalu",
      },
      savingRate: {
        title: "Rasio Tabungan",
        value: 37.9,
        previousValue: 24.1,
        changePercentage: 13.8,
        isPositive: true,
        trendText: "target tercapai (>30%)",
      },
    },
  },
  last_month: {
    period: "last_month",
    totalBalance: 21250000,
    totalIncome: 11800000,
    totalExpense: 8950000,
    netCashflow: 2850000,
    savingRate: 24.1,
    kpis: {
      balance: {
        title: "Total Saldo Kas",
        value: 21250000,
        previousValue: 19400000,
        changePercentage: 9.5,
        isPositive: true,
        trendText: "vs 2 bulan lalu",
      },
      income: {
        title: "Total Pemasukan",
        value: 11800000,
        previousValue: 10500000,
        changePercentage: 12.3,
        isPositive: true,
        trendText: "vs 2 bulan lalu",
      },
      expense: {
        title: "Total Pengeluaran",
        value: 8950000,
        previousValue: 8600000,
        changePercentage: 4.0,
        isPositive: false,
        trendText: "peningkatan biaya",
      },
      savingRate: {
        title: "Rasio Tabungan",
        value: 24.1,
        previousValue: 18.0,
        changePercentage: 6.1,
        isPositive: true,
        trendText: "stabil bertumbuh",
      },
    },
  },
  this_year: {
    period: "this_year",
    totalBalance: 25070000,
    totalIncome: 98400000,
    totalExpense: 64200000,
    netCashflow: 34200000,
    savingRate: 34.7,
    kpis: {
      balance: {
        title: "Total Saldo Kas",
        value: 25070000,
        previousValue: 14500000,
        changePercentage: 72.8,
        isPositive: true,
        trendText: "YoY growth",
      },
      income: {
        title: "Total Pemasukan (YTD)",
        value: 98400000,
        previousValue: 78000000,
        changePercentage: 26.1,
        isPositive: true,
        trendText: "vs periode tahun lalu",
      },
      expense: {
        title: "Total Pengeluaran (YTD)",
        value: 64200000,
        previousValue: 56000000,
        changePercentage: 14.6,
        isPositive: false,
        trendText: "inflasi & ekspansi",
      },
      savingRate: {
        title: "Rata-rata Rasio Simpan",
        value: 34.7,
        previousValue: 28.2,
        changePercentage: 6.5,
        isPositive: true,
        trendText: "kondisi sehat",
      },
    },
  },
};

export const MOCK_MONTHLY_CASHFLOW: CashflowPoint[] = [
  { label: "Mar", income: 9400000, expense: 7100000, net: 2300000 },
  { label: "Apr", income: 10200000, expense: 7800000, net: 2400000 },
  { label: "Mei", income: 12500000, expense: 8400000, net: 4100000 },
  { label: "Jun", income: 11000000, expense: 7900000, net: 3100000 },
  { label: "Jul", income: 11800000, expense: 8950000, net: 2850000 },
  { label: "Agu", income: 13550000, expense: 8415000, net: 5135000 },
];

export const MOCK_WEEKLY_CASHFLOW: CashflowPoint[] = [
  { label: "Minggu 1", income: 2950000, expense: 2100000, net: 850000 },
  { label: "Minggu 2", income: 3200000, expense: 1950000, net: 1250000 },
  { label: "Minggu 3", income: 4100000, expense: 2450000, net: 1650000 },
  { label: "Minggu 4", income: 3300000, expense: 1915000, net: 1385000 },
];

export const MOCK_CATEGORY_BREAKDOWN: CategoryBreakdownPoint[] = [
  {
    name: "Operasional Usaha",
    value: 3850000,
    color: "#2DD4BF", // Teal
    percentage: 45.7,
    iconName: "Briefcase",
  },
  {
    name: "Belanja & Kebutuhan",
    value: 1720000,
    color: "#38BDF8", // Sky Blue
    percentage: 20.4,
    iconName: "ShoppingCart",
  },
  {
    name: "Makanan & Minuman",
    value: 1450000,
    color: "#FBBF24", // Amber
    percentage: 17.2,
    iconName: "Utensils",
  },
  {
    name: "Utilitas & Tagihan",
    value: 875000,
    color: "#A78BFA", // Purple
    percentage: 10.4,
    iconName: "Zap",
  },
  {
    name: "Transportasi",
    value: 520000,
    color: "#34D399", // Emerald
    percentage: 6.3,
    iconName: "Car",
  },
];

export function formatCurrency(amount: number): string {
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
}

export function formatShortCurrency(amount: number): string {
  if (Math.abs(amount) >= 1_000_000_000) {
    return `Rp ${(amount / 1_000_000_000).toFixed(1)} M`;
  }
  if (Math.abs(amount) >= 1_000_000) {
    return `Rp ${(amount / 1_000_000).toFixed(1)} jt`;
  }
  if (Math.abs(amount) >= 1_000) {
    return `Rp ${(amount / 1_000).toFixed(0)} rb`;
  }
  return `Rp ${amount}`;
}

export function formatPercentage(value: number): string {
  return `${value.toFixed(1)}%`;
}

export function formatDateIndo(dateStr: string): string {
  try {
    const date = new Date(dateStr);
    return date.toLocaleDateString("id-ID", {
      day: "numeric",
      month: "short",
      year: "numeric",
    });
  } catch {
    return dateStr;
  }
}
