import { 
  GoogleAccountInfo, 
  SyncedSheetItem, 
  SheetTemplate, 
  SyncHistoryEntry,
  ColumnMappingItem 
} from "./types";

export const INITIAL_GOOGLE_ACCOUNT: GoogleAccountInfo = {
  isConnected: false,
  email: "",
  name: "",
  avatarUrl: "",
  connectedAt: "",
  lastUsedAt: new Date().toISOString(),
  autoSyncEnabled: true,
  quotaUsedPercent: 0,
  grantedScopes: [],
};

export const DEFAULT_COLUMN_MAPPINGS: ColumnMappingItem[] = [
  { sourceColumn: "Tanggal", targetField: "date", dataType: "date", isRequired: true },
  { sourceColumn: "Tipe (Masuk/Keluar)", targetField: "type", dataType: "string", isRequired: true },
  { sourceColumn: "Kategori", targetField: "category", dataType: "string", isRequired: true },
  { sourceColumn: "Nominal (IDR)", targetField: "amount", dataType: "number", isRequired: true },
  { sourceColumn: "Deskripsi", targetField: "description", dataType: "string", isRequired: false },
  { sourceColumn: "Rekening / Dompet", targetField: "account", dataType: "string", isRequired: true },
  { sourceColumn: "Status Verifikasi", targetField: "status", dataType: "string", isRequired: false, isReadOnly: true },
];

export const SHEET_TEMPLATES: SheetTemplate[] = [
  {
    id: "tpl-income-expense",
    name: "Analisis Pemasukan & Pengeluaran Bulanan",
    category: "income_expense",
    categoryLabel: "Analisis Arus Kas",
    description: "Rekap otomatis pendapatan vs beban usaha dengan pivot kategori, rasio margin, dan grafik tren 30 hari.",
    longDescription: "Templat komprehensif yang memecah pendapatan berdasarkan sumber omzet dan pengeluaran per pos operasional. Dilengkapi formula pivot otomatis, margin bersih harian, dan tabel perbandingan mingguan.",
    formulas: ["=SUM(D2:D100)", "=AVERAGE(D2:D100)", "=QUERY(A2:E, \"SELECT C, SUM(D) GROUP BY C\")", "=IF(B2=\"Pemasukan\", D2, -D2)"],
    sampleColumns: ["Tanggal", "Jenis", "Kategori", "Nominal (Rp)", "Keterangan", "Sumber Akun"],
    sampleRows: [
      ["2024-03-15", "Pemasukan", "Omzet Penjualan", 4500000, "Penjualan batch 1 toko online", "BCA Bisnis"],
      ["2024-03-16", "Pengeluaran", "Bahan Baku", 1850000, "Restock packaging ramah lingkungan", "Mandiri Utama"],
      ["2024-03-17", "Pengeluaran", "Logistik & Ekspedisi", 320000, "Ongkir pengiriman kilat Jabodetabek", "GoPay Usaha"],
      ["2024-03-18", "Pemasukan", "Jasa Konsultasi", 2000000, "Invoice konsultasi klien A", "BCA Bisnis"],
      ["2024-03-19", "Pengeluaran", "Listrik & Internet", 650000, "Tagihan bulanan kantor studio", "BCA Bisnis"],
    ],
    chartTypes: ["Area Chart (Tren Saldo)", "Donut Chart (Breakdown Beban)", "Bar Chart (In vs Out)"],
    recommendedFrequency: "realtime",
    isPopular: true,
    usageCount: 428,
  },
  {
    id: "tpl-budget-performance",
    name: "Laporan Performa Anggaran & Varians",
    category: "budget",
    categoryLabel: "Kontrol Anggaran",
    description: "Evaluasi realisasi pengeluaran terhadap batas anggaran dengan indikator peringatan over-budget otomatis.",
    longDescription: "Membantu pemilik usaha dan individu memantau disiplin anggaran per pos. Menghitung otomatis varians nominal dan persentase deviasi, memberi kode warna peringatan (Aman, Waspada, Over).",
    formulas: ["=B2-C2 (Varians Nominal)", "=(C2/B2)*100 (Persentase Realisasi)", "=IF(C2>B2, \"OVER BUDGET\", \"AMAN\")"],
    sampleColumns: ["Pos Anggaran", "Plafon Anggaran", "Realisasi Finusa", "Sisa Plafon", "Persentase", "Status"],
    sampleRows: [
      ["Pemasaran & Iklan", 3000000, 2450000, 550000, "81.6%", "Waspada"],
      ["Operasional & Utilitas", 2000000, 1650000, 350000, "82.5%", "Waspada"],
      ["Gaji & Freelance", 12000000, 12000000, 0, "100.0%", "Penuh"],
      ["Peralatan & Hardware", 1500000, 890000, 610000, "59.3%", "Aman"],
      ["Sewa Tempat & Server", 1200000, 1200000, 0, "100.0%", "Penuh"],
    ],
    chartTypes: ["Bullet Chart (Target vs Aktual)", "Horizontal Bar (Varians Pos)"],
    recommendedFrequency: "daily",
    isPopular: true,
    usageCount: 312,
  },
  {
    id: "tpl-cashflow-projection",
    name: "Proyeksi Arus Kas 3 Bulan Kedepan",
    category: "cashflow",
    categoryLabel: "Perencanaan Likuiditas",
    description: "Prediksi saldo kas masa depan berdasarkan tren historis, piutang masuk, dan pengeluaran berulang.",
    longDescription: "Simulasi likuiditas dinamis yang memproyeksikan posisi kas akhir bulan dengan memperhitungkan recurring bills dan expected receivables sehingga terhindar dari defisit modal kerja.",
    formulas: ["=FORECAST(A15, B2:B14, A2:A14)", "=TREND(C2:C14)", "=SUM(Pemasukan_Estimasi)-SUM(Beban_Rutin)"],
    sampleColumns: ["Periode Bulan", "Saldo Awal", "Est. Penerimaan", "Est. Pengeluaran", "Net Kas", "Proyeksi Saldo Akhir"],
    sampleRows: [
      ["April 2024 (Aktual)", 18500000, 24000000, 16200000, 7800000, 26300000],
      ["Mei 2024 (Proyeksi M1)", 26300000, 26500000, 17800000, 8700000, 35000000],
      ["Juni 2024 (Proyeksi M2)", 35000000, 28000000, 19000000, 9000000, 44000000],
      ["Juli 2024 (Proyeksi M3)", 44000000, 31000000, 20500000, 10500000, 54500000],
    ],
    chartTypes: ["Forecast Line Chart with Confidence Interval", "Waterfall Chart"],
    recommendedFrequency: "weekly",
    isPopular: false,
    usageCount: 189,
  },
  {
    id: "tpl-tax-summary",
    name: "Rekap Pajak UMKM & Potongan PPh Final",
    category: "tax",
    categoryLabel: "Kepatuhan Pajak",
    description: "Kompilasi omzet bruto bulanan dengan kalkulator PPh Final 0.5% (PP 55/2022) dan arsip bukti setor.",
    longDescription: "Didesain khusus untuk kepatuhan pajak UMKM Indonesia. Memisahkan otomatis transaksi yang dikenakan PPh Final 0.5%, non-objek pajak, dan potongan invoice pihak ketiga.",
    formulas: ["=IF(Omzet_Tahunan<500000000, 0, Omzet_Kena_Pajak*0.005)", "=SUMIF(B:B, \"Omzet Bruto\", D:D)"],
    sampleColumns: ["Masa Pajak", "Omzet Bruto", "Akumulasi YTD", "Dasar Pengenaan", "PPh Final 0.5%", "Status Setor (NTPN)"],
    sampleRows: [
      ["Januari 2024", 42000000, 42000000, 0, 0, "N/A (Bebas PTKP 500Jt)"],
      ["Februari 2024", 48500000, 90500000, 0, 0, "N/A (Bebas PTKP 500Jt)"],
      ["Maret 2024", 51200000, 141700000, 0, 0, "N/A (Bebas PTKP 500Jt)"],
      ["April 2024", 55000000, 196700000, 0, 0, "N/A (Bebas PTKP 500Jt)"],
    ],
    chartTypes: ["Cumulative Bar Chart", "Tax Liability Timeline"],
    recommendedFrequency: "monthly",
    isPopular: false,
    usageCount: 145,
  },
  {
    id: "tpl-pnl-statement",
    name: "Laporan Laba Rugi Standar (P&L Statement)",
    category: "pnl",
    categoryLabel: "Laporan Keuangan Formal",
    description: "Struktur formal P&L: Pendapatan Usaha, HPP/COGS, Laba Kotor, Biaya Operasional, dan Laba Bersih.",
    longDescription: "Format laporan laba rugi standar akuntansi yang siap diserahkan kepada investor, pengelola usaha, atau manajemen internal dengan subtotal berjenjang yang selalu sinkron dengan pembukuan Finusa.",
    formulas: ["=Pendapatan - HPP (Laba Kotor)", "=Laba_Kotor - Total_Beban (EBITDA)", "=Laba_Operasional - Pajak_Bunga"],
    sampleColumns: ["Komponen Laba Rugi", "Realisasi Q1", "Realisasi Q2", "Pertumbuhan QoQ (%)", "Catatan Akuntan"],
    sampleRows: [
      ["Pendapatan Bruto Penjualan", 145000000, 168000000, "+15.8%", "Termasuk revenue e-commerce"],
      ["Harga Pokok Penjualan (HPP)", 62000000, 71500000, "+15.3%", "Bahan baku & upah langsung"],
      ["LABA KOTOR (Gross Profit)", 83000000, 96500000, "+16.2%", "Margin kotor 57.4%"],
      ["Total Biaya Operasional", 34500000, 36200000, "+4.9%", "Sewa, marketing, software"],
      ["LABA BERSIH OPERASIONAL", 48500000, 60300000, "+24.3%", "EBIT margin 35.8%"],
    ],
    chartTypes: ["Waterfall P&L Breakdown", "EBITDA Margin Tracker"],
    recommendedFrequency: "daily",
    isPopular: true,
    usageCount: 520,
  },
];

export const INITIAL_SYNCED_SHEETS: SyncedSheetItem[] = [];

export const INITIAL_SYNC_HISTORY: SyncHistoryEntry[] = [];
